name: carnd
dependencies:
    - python==3.10.10
    - numpy
    - matplotlib
    - jupyter
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
    - pip:
        - moviepy
        - opencv-python
        - requests
        - tensorflow
        - keras
        - docopt
        - glob3
